#!/bin/sh

binary=chittyrc
test -x "./$binary" || { 
    echo; 
    echo "chirc executable does not exist. Cannot run tests."; 
    echo; 
    exit 1; 
}
python3 -m pytest tests/ --chirc-exe=$binary --randomize-ports --json=tests/report.json --html=tests/report.html $TEST_ARGS
